### ISSUE TITLE
Tutorial to use this package

### ISSUE THREAD

**Issue by KunFang93** [vlukiyanov/pt-dec#22]
I was wondering if there is any tutorial to use this package? Thanks!

**Comment by vlukiyanov** [comment]
This just attempts to implement the DEC method in PyTorch; I wouldn't suggest using this code for anything other than learning or research. An example using MNIST data can be found in examples/mnist/mnist.py, which is probably the nearest thing. In the paper the authors suggest keeping the autoencoder structure reasonably constant so that should be a good starting point.
