### ISSUE TITLE
Working with color image data

### ISSUE THREAD

**Issue by arminbazza** [vlukiyanov/pt-dec#29]
Hey, thank you so much for your awesome implementation! I have one problem that I could use some help with. How would you get this to work with color images, such as STL-10? 

In the paper I see that they mention "concatenating HOG feature and a 8-by-8 color map to use as input to all algorithms." Unfortunately, I'm finding the original code a bit difficult to sift through... 

Do you have any recommendations on how to proceed?

**Comment by arminbazza** [comment]
For what it's worth, I decided to move forward using a pre-trained ResNet as my feature extraction method. But, I would still like to hear your comments on it @vlukiyanov

**Comment by vlukiyanov** [comment]
Hey, apologies for the delayed reply. Unfortunately its been quite a while since I last looked into this so wouldn't be able to say; if you do manage to make this work would be great to get a PR as an example, since as you mentioned their original code is a bit hard to grasp when studying this method.
